---
- name: "add distribution-specific variables"
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: "add Debian Wheezy workaround"
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when:
    - "ansible_distribution == 'Debian'"
    - "ansible_distribution_release == 'wheezy'"

- name: "add Debian Bullseye workaround"
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when:
    - "ansible_distribution == 'Debian'"
    - "ansible_distribution_release == 'bullseye'"

- name: "install powermgmt-base"
  ansible.builtin.apt:
    pkg:
    state: "present"
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: "yes"
  when: "unattended_only_on_ac_power"

- name: "install unattended-upgrades"
  ansible.builtin.apt:
    pkg: "unattended-upgrades"
    state: "present"
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: "yes"

- name: "install reboot dependencies"
  ansible.builtin.include: "reboot.yml"
  when: "unattended_automatic_reboot | bool"

- name: "create APT auto-upgrades configuration"
  ansible.builtin.template:
    src: "auto-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "create unattended-upgrades configuration"
  ansible.builtin.template:
    src: "unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: "root"
    group: "root"
    mode: "0644"
